import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :todo_list, TodoListWeb.Endpoint,
url: [host: "localhost", port: 4000],
check_origin: ["http://localhost:4000"],
cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Hackney

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

config :todo_list, TodoList.Repo,
  username: "postgres",
  password: "postgres",
  database: "todo_list_prod",
  hostname: "postgres",
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10")

  config :todo_list, TodoList.Mailer,
  adapter: Swoosh.Adapters.Mailgun,
  api_key: System.get_env("MAILGUN_API_KEY"),
  domain: "bubastodolist.me"
